deepset-ai/hayhooks

src/hayhooks/cli/run/__init__.py
src/hayhooks/server/app.py
src/hayhooks/server/handlers/deploy.py
src/hayhooks/server/utils/__init__.py
src/hayhooks/server/utils/deploy_utils.py

Add the possibility to pass `--pipelines-dir` in `hayhooks run`.
These pipelines are automatically deployed at startup.

Load pipelines at startup

---

src/hayhooks/server/handlers/deploy.py

This fixes an error I get when running "hayhooks deploy pipeline.yml". The error is "TypeError: object dict can't be used in 'await' expression" from
File "/hayhooks/server/handlers/deploy.py", line 7, in deploy
return await deploy_pipeline_def(app, pipeline_def)

Removed unneeded 'await' causing error on hayhooks deploy

---

src/hayhooks/server/app.py

Updated response:
```json
{
"swagger_docs" : "http://localhost:1416/docs",
"deploy_pipeline" : "http://localhost:1416/deploy",
"draw_pipeline" : "http://localhost:1416/draw{/pipeline_name}",
"server_status" : "http://localhost:1416/status",
"undeploy_pipeline" : "http://localhost:1416/undeploy{/pipeline_name}",
}
```

Enhacne the response of '/' endpoint

---

src/hayhooks/server/pipelines/models.py
src/hayhooks/server/utils/create_valid_type.py

Currently if you try to go to http://localhost:1416/docs#/ with an extractive pipeline, an error will be thrown because the response class, ExtractedAnswer, contains a DataFrame, which pydantic is unable to serialize. I have added a function create_valid_type that creates a new type, replacing invalid types with those specified. This also means that it is no longer necessary to convert Documents to HaystackDocument for validation by pydantic.

Fixed JSON Schema Serialization for Components

---

README.md
src/hayhooks/cli/__init__.py
src/hayhooks/cli/deploy/__init__.py
src/hayhooks/cli/status/__init__.py
src/hayhooks/cli/undeploy/__init__.py

Sometimes for development purposes we need to skip ssl verification, otherwise we face the ssl verification error for unverified certificates

Disable ssl verification

---

README.md
docker/docker-bake.hcl

Changed `custom-components`  to `custom_components` for reasons detailed in https://github.com/deepset-ai/hayhooks/issues/28

Renamed custom-components to custom_components

---

src/hayhooks/server/pipelines/models.py
src/hayhooks/server/utils/create_valid_type.py

`TypedDict` is unable to handle `Union[type, NoneType]`, it requires the type to be `Optional[type]`. I've added a small fix for that. This fixes #25.  
Example traceback with deploying a pipeline that contains `DocumentJoiner`: 
```
Traceback (most recent call last):
...
File "/Users/rustynail/Projects/github/hayhooks/src/hayhooks/server/__init__.py", line 1, in <module>
from hayhooks.server.app import app
File "/Users/rustynail/Projects/github/hayhooks/src/hayhooks/server/app.py", line 32, in <module>
app = create_app()
File "/Users/rustynail/Projects/github/hayhooks/src/hayhooks/server/app.py", line 27, in create_app
deployed_pipeline = deploy_pipeline_def(app, pipeline_defintion)
File "/Users/rustynail/Projects/github/hayhooks/src/hayhooks/server/utils/deploy_utils.py", line 20, in …
```

convert union type with none to optional

---

src/hayhooks/server/utils/deploy_utils.py

This PR enhances the deploy_utils.py file to support asynchronous execution of the `pipeline_run` method using `run_in_threadpool`. This change allows the server to handle multiple pipeline requests concurrently, improving performance and efficiency.
I've already tested it locally with a `docker-compose.yml` with 
```
services:
hayhooks:
image: deepset/hayhooks:main
ports:
- "1416:1416"
volumes:
- ./pipelines:/opt/pipelines
- ./custom_components:/opt/custom_components
- ./my_custom_deploy_utils.py:/opt/venv/lib/python3.12/site-packages/hayhooks/server/utils/deploy_utils.py
environment:
- PYTHONPATH=/opt
- HAYHOOKS_ADDITIONAL_PYTHONPATH=/opt/custom_components
```
where `my_custom_deploy_utils.py` is the adjusted file (with run_in_threadpool etc)
If you need additional testing resources, …

deploy_utils.py w async execution support

---

pyproject.toml

Minor change to avoid using latest python version (which is still not fully supported by packages like `torch` or `sentence_transformers`)

Fix Python version requirement to >=3.7,<3.13

---

docs/deployment_guidelines.md

The purpose of this document is simply to make people more aware of how pipelines can be deployed and called on Hayhooks in different environment (single vs multiple workers).
TODO:

Draft deployment guidelines

---

.github/workflows/tests.yml
pyproject.toml
tests/test_handle_callable_type.py

With this I am adding a basic action to run tests on Python `3.9`-`3.12` (I've removed `3.7`-`3.8` support which was present in `pyproject.toml`).

Add basic action to run current tests

---

src/hayhooks/server/handlers/status.py
src/hayhooks/server/pipelines/registry.py
tests/conftest.py
tests/test_it_deploy.py
tests/test_it_draw.py
tests/test_it_handling_deploy_exceptions.py
tests/test_it_status.py

With this, I've sligthly refactored some routes and added missing tests. This will help upcoming routes refactoring.

Add missing tests for some endpoints before route refactoring

---

src/hayhooks/server/__init__.py
src/hayhooks/server/app.py
src/hayhooks/server/handlers/__init__.py
src/hayhooks/server/handlers/deploy.py
src/hayhooks/server/routers/__init__.py
src/hayhooks/server/routers/deploy.py
src/hayhooks/server/routers/draw.py
src/hayhooks/server/routers/status.py
src/hayhooks/server/routers/undeploy.py

I've refactored how currently the API routes are handled. 
Using [APIRouter](https://fastapi.tiangolo.com/reference/apirouter/), we can avoid circular imports and mypy type issues that we hd before.

Refactored API route handlers using APIRouter(s)

---

src/hayhooks/server/routers/openai.py
src/hayhooks/server/utils/base_pipeline_wrapper.py
src/hayhooks/server/utils/deploy_utils.py
tests/test_files/files/chat_with_website/pipeline_wrapper.py
tests/test_files/files/run_api_error/pipeline_wrapper.py
tests/test_it_deploy_files.py

I've spotted a bad bug on which we were passing the wrong params to the `run_in_threadpool` method created on dynamic route `{pipeline_name}/run` (see changes in `deploy_utils.py`).
I've fixed it and also:
- fix some type issues (in `openai` route hander and BasePipelineWrapper class)
- made test `test_pipeline_endpoint_error_handling` more robust

Fix /run dynamic route params

---

.env.example
.gitignore
src/hayhooks/cli/deploy_files/__init__.py
src/hayhooks/cli/run/__init__.py
src/hayhooks/server/__init__.py
src/hayhooks/server/app.py
src/hayhooks/server/utils/deploy_utils.py
src/hayhooks/settings.py
tests/conftest.py
tests/test_deploy_at_startup.py
tests/test_deploy_utils.py
tests/test_it_deploy.py
tests/test_it_deploy_files.py
tests/test_it_draw.py
tests/test_it_handling_deploy_exceptions.py
tests/test_it_openai.py
tests/test_it_status.py
tests/test_settings.py

This may seems a bit convoluted, but actually contains minor refactoring and improvements:
I've removed the `app` creation at module level in `app.py`. We were instantiating `app` each time that module is imported and this is not optimal. Now we're using only the `create_app` helper.
This will allow users to programmatically create their `app` instance, adding required middlewares when needed (e.g. for CORS, authentication or authorization). It's also used in `hayhooks run` CLI command. This will be better documented on another PR.
- Removed the various `TestClient` instances around test files and used a single one as a fixture in `conftest.py`. 
- Override `settings` for tests, creating `pipelines` dir in `tests` dir. 
- Automatic cleanup of `pipelines` dir after each test module run. …

Remove app creation at module level + refactoring

---

.env.example
src/hayhooks/settings.py
tests/test_settings.py

As stated in README, env vars for settings should have `HAYHOOKS_*` format.
This actually add support for prefix (which was missing). Added also a test.

Support for `HAYHOOKS` env var prefix

---

src/hayhooks/settings.py

Found out that `load_dotenv()` doesn't use cwd by default. Fixed it using an internal helper.

Correctly use cwd for loading .env file

---

src/hayhooks/cli/base.py
src/hayhooks/cli/pipeline.py
tests/test_cli.py

This is to enable support of `-n` as well as `--name` for options, so commands like:
```bash
hayhooks pipeline deploy-files -n chat_with_website examples/chat_with_website
```
Will work as expected. I've also added a test for tracking this.

Add support for short and long option names

---

README.md
examples/chat_with_website/pipeline_wrapper.py
examples/chat_with_website_streaming/pipeline_wrapper.py
src/hayhooks/__init__.py
src/hayhooks/server/pipelines/utils.py
tests/test_files/files/chat_with_website/pipeline_wrapper.py
tests/test_files/files/chat_with_website_streaming/pipeline_wrapper.py
tests/test_files/files/missing_methods/pipeline_wrapper.py
tests/test_files/files/no_chat/pipeline_wrapper.py
tests/test_files/files/run_api_error/pipeline_wrapper.py
tests/test_files/files/setup_error/pipeline_wrapper.py
tests/test_files/mixed/chat_with_website/pipeline_wrapper.py

I've exposed some imports directly in `hayhooks` init to make them cleaner when it comes to implement a `BasePipelineWrapper` and so create a pipeline wrapper.
Basically, here's how they looked:
```python
from hayhooks.server.pipelines.utils import get_last_user_message, streaming_generator
from hayhooks.server.utils.base_pipeline_wrapper import BasePipelineWrapper
from hayhooks.server.logger import log
```
And this is how they look now:
```python
from hayhooks import get_last_user_message, BasePipelineWrapper, log, streaming_generator
```
I've also updated README and `/examples` folder.

Cleaner imports when implementing a BasePipelineWrapper

---

README.md
src/hayhooks/__init__.py

This is to add an example to create the `hayhooks` app instance programmatically.
Useful if one want to add custom routes or middlewares to the app instance.
I've exported the function which is used as a factory to create the app instance and updated README with an example script.

Run hayhooks programmatically

---

README.md
src/hayhooks/cli/pipeline.py
src/hayhooks/server/routers/deploy.py
src/hayhooks/server/utils/deploy_utils.py
tests/conftest.py
tests/test_deploy_utils.py
tests/test_it_deploy_files.py

This is to:
- Support `overwrite` option on `deploy-files` command and `/deploy-files` API route.
- Expose `skip-saving-files` option on `deploy-files` command and `/deploy-files` API route.
The main reason behind this is to ease the development phase of the pipeline wrapper. So now one can deploy a pipeline multiple subsequent times doing:
```shell
hayhooks pipeline deploy-files -n {pipeline_name} {pipeline_folder_path} --overwrite
```
multiple times without getting the `409 conflict - pipeline already exists` error. The pipeline files will be replaced and the pipeline will be reloaded without the need to manually removing files or call `/undeploy` API.
I've also exposed the `skip-saving-files` option, which allows deploy without saving files (so deployed pipelines will not be reloaded …

Support 'overwrite' and 'skip-saving-files' options on pipeline deploy

---

src/hayhooks/server/app.py
src/hayhooks/server/utils/deploy_utils.py
src/hayhooks/settings.py
tests/test_settings.py

This is a minor refactor to move CORS validation function at app instance creation time (previously was a settings creation level). This is to avoid trigger CORS validation when it's not needed and also to make code cleaner.

Move CORS validation at app instance creation time

---

src/hayhooks/server/utils/deploy_utils.py
tests/test_deploy_utils.py
tests/test_it_deploy_files.py

I noticed a nasty bug: if you deploy consequently a pipeline using `--overwrite` option (or `overwrite` param on `/deploy-files` API) doesn't actually run the updated code. 
In the existing tests, we were adding to updated files the `run_chat_completion` method (and it was working), but we didn't try e.g. to update the code of `run_api`. Indeed it wasn't working due to python import cache and due to the fact that FastAPI doesn't replace the existing route using `app.add_api_route`.
With this, we:
- Clear the module from sys.modules if it exists to ensure a fresh load
- Clear existing pipeline run API route if it exists on FastAPI `app` instance
I've also added a test where we change the actual wrapper code between two deploys using `overwrite` option.

Deploying an updated pipeline with `overwrite` option should also run updated code

---

src/hayhooks/server/app.py
tests/test_settings.py

Fixes #82.
Explanation of previous situation is [here](https://github.com/deepset-ai/hayhooks/issues/82#issuecomment-2694529010).
With this, `additional_python_path` works correctly both via CLI and setting `HAYHOOKS_ADDITIONAL_PYTHON_PATH` env var.

Make additional_python_path setting work also settings related env var

---

pyproject.toml
src/hayhooks/server/pipelines/models.py

With this:
- I've removed the import of `DataFrame` from `pandas` which was used in legacy YAML-only based deployment type mapping
- Pin Haystack to >=2.11.0 to ensure that `DataFrame` is not anymore inside `Document`

Remove pandas reference and pin haystack-ai to >=2.11.0

---

src/hayhooks/server/app.py
src/hayhooks/server/routers/deploy.py
src/hayhooks/server/routers/draw.py
src/hayhooks/server/routers/openai.py
src/hayhooks/server/routers/status.py
src/hayhooks/server/routers/undeploy.py
src/hayhooks/settings.py
tests/test_it_deploy_files.py
tests/test_it_openai.py
tests/test_undeploy.py

TL;DR
This PR doesn't add any new feature, but rather improve generated OpenAPI / Swagger / Redocly documentation in order to ease the use of Hayhooks as an [OpenAPI Tool Server](https://docs.openwebui.com/openapi-servers/).
---
In order to enhance usare of Hayhooks as an [OpenAPI Tool Server by Open WebUI](https://docs.openwebui.com/openapi-servers/open-webui), we need to have a more description app title, description and version. 
Also, every Pydantic model needs to be better documented, possibly with examples.
This way it will be possible to use the entire Hayhooks as a Tool, so an agent could run / deploy / check pipelines. I'll plan to exposes the functionalities for MCP Server too.
This basically leads to a **far better** open-webui integration than acting like an open-webui …

Improve app and models metadata

---

README.md

Since we have updated deployment docs pages on Haystack docs, this is adding reference on README to:
- Docker doc page: <https://docs.haystack.deepset.ai/docs/docker>
- k8s doc page: <https://docs.haystack.deepset.ai/docs/kubernetes>

Add reference to updated Docker/k8s deployment pages on README

---

README.md
pyproject.toml
src/hayhooks/server/utils/deploy_utils.py
tests/test_deploy_utils.py
tests/test_mcp.py

This will add better description of `run_api` params / return type to dynamically create request / response pydantic models using [docstring_parser](https://github.com/rr-/docstring_parser) to automatically parse `run_api` docstring.
For example, if you have a `run_api` like:
```python
def run_api(question: str, urls: List[str]) -> str:
"""
Ask a question about one or more websites using a Haystack pipeline.
Args:
question: The question to ask.
urls: List of URLs to fetch.
Returns:
The answer to the question.
"""
...
```
It will add proper description, defaults (if present) and type to each param on pydantic model schema for `question`, `urls` and the return type. 
This improved description will improve Hayhooks usage as OpenAPI Tool or MCP Tool.

Improve `run_api` dynamic schema creation 

---

src/hayhooks/settings.py
tests/test_settings.py

This PR address a minor bug where we set an incorrect default value for `pipelines_dir`. 
Indeed, if you do `hayhooks run` from a fresh python venv, you'll find `pipelines` folder by default in the following (wrong) path:
```shell
{PROJECT_FOLDER}/.venv/lib/python3.12/pipelines
```
while it should be in `cwd()/pipelines`, so:
```shell
{PROJECT_FOLDER}/pipelines
```
Of course, if you were manually set `pipelines_dir` or `HAYHOOKS_PIPELINES_DIR`, everything works as expected.

Fix `pipelines_dir` default path

---

pyproject.toml
src/hayhooks/cli/mcp.py
src/hayhooks/server/routers/undeploy.py
src/hayhooks/server/utils/deploy_utils.py
src/hayhooks/server/utils/mcp_utils.py
tests/test_deploy_utils.py
tests/test_it_mcp_server.py
tests/test_mcp.py

This is to expose core Hayhooks APIs as MCP Tools. 
This will enable, from any MCP Client, the following actions:
- `get_all_pipeline_statuses` (Get the status of all pipelines and list available pipeline names.)
- `get_pipeline_status` Get status of a specific pipeline)
- `undeploy_pipeline` (Undeploy a pipeline. Removes a pipeline from the registry, its API routes, and deletes its files)
- `deploy_pipeline` (Deploy a pipeline from files (pipeline_wrapper.py and other files)
Of course, any deployed pipeline will be listed as a tool as well.

Core Hayhooks MCP Tools

---

src/hayhooks/server/app.py

Simple change to set `connect_timeout` and `read_timeout` by default to 5s to make `get_package_version_from_pypi` to fail faster if no internet connection is available.

Make `get_package_version_from_pypi` to fail faster if no internet connection is available

---

README.md
pyproject.toml
src/hayhooks/cli/mcp.py
src/hayhooks/server/utils/mcp_utils.py
tests/conftest.py
tests/test_it_mcp_server.py

This adds (stateless) [Streamable HTTP MCP transport](https://modelcontextprotocol.io/docs/concepts/transports#streamable-http) support.
The SSE transport (now deprecated) will still run together with Streamable HTTP one to maintain the compatibility with Claude Desktop, [which doesn't supports remote MCP Servers on free tier](https://support.anthropic.com/en/articles/11503834-building-custom-integrations-via-remote-mcp-servers) (only on paid ones).
On IDEs like Cursor, stateless Streamable HTTP will work smoothly.
So by default they will be both available at:
- <http://localhost:1417/sse> (SSE - deprecated)
- <http://localhost:1417/mcp> (HTTP)
Note that added Streamable HTTP transport doesn't yet support an Event Store for making client sessions resumable.
I've added two lower-level …

Add Streamable HTTP MCP transport

---

examples/pipeline_wrappers/open_webui_agent_events/README.md

As title, I've added a specific README for [open-webui events](https://docs.openwebui.com/features/plugin/events/) example where we also describe the currently supported events (this was missing in the main README).

Add specific README for events example

---

examples/pipeline_wrappers/async_question_answer/question_answer.yml
examples/pipeline_wrappers/chat_with_website/chat_with_website.yml
examples/pipeline_wrappers/chat_with_website_mcp/chat_with_website.yml
examples/pipeline_wrappers/chat_with_website_streaming/chat_with_website.yml
examples/rag_indexing_query/query_pipeline/pipeline_wrapper.py
tests/test_files/files/async_chat_with_website/chat_with_website.yml
tests/test_files/files/async_chat_with_website_streaming/chat_with_website.yml
tests/test_files/files/async_question_answer/question_answer.yml
tests/test_files/files/chat_with_website/chat_with_website.yml
tests/test_files/files/chat_with_website_mcp/chat_with_website.yml
tests/test_files/files/chat_with_website_streaming/chat_with_website.yml
tests/test_files/files/no_wrapper/chat_with_website.yml
tests/test_files/mixed/basic_rag_pipeline.yml
tests/test_files/mixed/chat_with_website/chat_with_website.yml
tests/test_files/yaml/broken_rag_pipeline.yml
tests/test_files/yaml/working_pipelines/basic_rag_pipeline.yml
tests/test_files/yaml/working_pipelines/chat_with_website.yml
tests/test_files/yaml/working_pipelines/pipeline_qdrant.yml
tests/test_it_pipeline_utils.py

In #155, I set `log_cli = true` in pytest options. https://docs.pytest.org/en/stable/how-to/logging.html#live-logs
I immediately started to see a lot of warnings coming from Prompt Builder and Chat Prompt Builder.
In this small PR, I am setting `required_variables=True` in Prompt Builder and Chat Prompt Builder to avoid all of them.
In any case, I think it can be helpful to have log records in the CLI.

chore: set required_variables in Prompt Builders to reduce noise in logs

---

pyproject.toml

This is simply to avoid such situations (which could happen if you se a [MyPy extension](https://marketplace.visualstudio.com/items?itemName=ms-python.mypy-type-checker) in your IDE)
My idea is to ignore errors for now, then take some time and see if it worth to test types also in tests modules (in another PR of course).

Make mypy ignore errors in tests.* modules
